### PR TITLE
Update firegento/fastsimpleimport required version

### LINKED ISSUE #127: Not compatible with PHP 8 due to dependencies
Whilst this module in itself doesn't specify any PHP requirements and the code is compatible with PHP 8, the dependency on `"firegento/fastsimpleimport": "1.3.4"` makes this module also not compatible. Firegento have resolved the PHP compatibility in version 2+ but the exact versioning used here makes it not possible to update that module individually.

Error:
during `bin/magento setup:di:compile`
image

Resolution:
modify the composer requirement for `firegento/fastsimpleimport` to either not specify a version, or so that version 2+ can be installed

### PR DESCRIPTION
**Pull request by NathanDayFE**
fixes #127 

Drop support for [firegento/fastsimpleimport](https://github.com/firegento/FireGento_FastSimpleImport2) `1.3.4` and require `^2.0`

### CODE REVIEW

**Comment by fredden** [comment]
@chevli please can we get this merged in and a new version released? Meanwhile we have to keep patching `firegento/fastsimpleimport` with composer-patches, which is annoying to maintain.

**Comment by NathanDayFE** [comment]
@paulpartington-cti any chance this can be reviewed and merged please

**Comment by paulpartington-cti** [comment]
@NathanDayFE Apologies for the delay, we will aim to get them reviewed and a new release sorted in the next few days.

**Comment by paulpartington-cti** [comment]
Merged into 3.2.0. Thanks!.

**Pull request merged**
